# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tenseal_DragonNetData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1btenseal_DragonNetData.proto\"<\n\tencrypted\x12\r\n\x05round\x18\x01 \x01(\x05\x12\x13\n\x0b\x63lient_rank\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\x0c\"+\n\x07gradenc\x12\x13\n\x0b\x63lient_rank\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\x0c\"\x1c\n\x0csendgradflag\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x05\".\n\x08sendgrad\x12\x13\n\x0b\x63lient_rank\x18\x01 \x01(\x05\x12\r\n\x05round\x18\x02 \x01(\x05\x32\x8f\x01\n\x10SafeTransmission\x12\'\n\rMiddleForward\x12\n.encrypted\x1a\n.encrypted\x12)\n\x0eMiddleBackward\x12\x08.gradenc\x1a\r.sendgradflag\x12\'\n\x0e\x42ottomBackward\x12\t.sendgrad\x1a\n.encryptedb\x06proto3')



_ENCRYPTED = DESCRIPTOR.message_types_by_name['encrypted']
_GRADENC = DESCRIPTOR.message_types_by_name['gradenc']
_SENDGRADFLAG = DESCRIPTOR.message_types_by_name['sendgradflag']
_SENDGRAD = DESCRIPTOR.message_types_by_name['sendgrad']
encrypted = _reflection.GeneratedProtocolMessageType('encrypted', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTED,
  '__module__' : 'tenseal_DragonNetData_pb2'
  # @@protoc_insertion_point(class_scope:encrypted)
  })
_sym_db.RegisterMessage(encrypted)

gradenc = _reflection.GeneratedProtocolMessageType('gradenc', (_message.Message,), {
  'DESCRIPTOR' : _GRADENC,
  '__module__' : 'tenseal_DragonNetData_pb2'
  # @@protoc_insertion_point(class_scope:gradenc)
  })
_sym_db.RegisterMessage(gradenc)

sendgradflag = _reflection.GeneratedProtocolMessageType('sendgradflag', (_message.Message,), {
  'DESCRIPTOR' : _SENDGRADFLAG,
  '__module__' : 'tenseal_DragonNetData_pb2'
  # @@protoc_insertion_point(class_scope:sendgradflag)
  })
_sym_db.RegisterMessage(sendgradflag)

sendgrad = _reflection.GeneratedProtocolMessageType('sendgrad', (_message.Message,), {
  'DESCRIPTOR' : _SENDGRAD,
  '__module__' : 'tenseal_DragonNetData_pb2'
  # @@protoc_insertion_point(class_scope:sendgrad)
  })
_sym_db.RegisterMessage(sendgrad)

_SAFETRANSMISSION = DESCRIPTOR.services_by_name['SafeTransmission']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENCRYPTED._serialized_start=31
  _ENCRYPTED._serialized_end=91
  _GRADENC._serialized_start=93
  _GRADENC._serialized_end=136
  _SENDGRADFLAG._serialized_start=138
  _SENDGRADFLAG._serialized_end=166
  _SENDGRAD._serialized_start=168
  _SENDGRAD._serialized_end=214
  _SAFETRANSMISSION._serialized_start=217
  _SAFETRANSMISSION._serialized_end=360
# @@protoc_insertion_point(module_scope)
